- name: Install catalogue components
  hosts: catalogue
  become: yes
  tasks:
  - name: Install NPM source
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: Install Nodejs
    ansible.builtin.yum:
      name: nodejs 
      state: installed

  - name: Checking whether roboshop user exists
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true

  - when: out.rc != 0
    name: add roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: checking the app directory
    ansible.builtin.stat: 
      path: /app
    register: directory

  - name: Printing the stat
    ansible.builtin.debug:
      msg: "Output is : {{directory}}"

  - when: directory.stat.exists == False
    name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Download the catalogue artifact
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: Extracting the catalogue artifact
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes


  - name: Installing dependencies
    ansible.builtin.command: npm install 
    args:
      chdir: /app

  - name: Copying catalogue.service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: Daemon reload
    ansible.builtin.systemd:
      daemon_reload: true

  - name: Starting and enabling catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: true

  
