- name: Installing Rabbitmq
  hosts: rabbitmq
  become: yes
  tasks: 
  - name: Configuring rabbitmq yum repos
    ansible.builtin.shell: "{{item}}"

    loop:
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
    - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"

  - name: Installing rabbitmq server
    ansible.builtin.yum:
      name: rabbitmq-server
      state: installed

  - name: restarting and enabling the server
    ansible.builtin.service:
      name: rabbitmq-server
      state: restarted
      enabled: yes

  - name: Create rabbitmq user
    ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

  - name: Giving permissions to the user
    ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"


