- name: Install user components
  hosts: user
  become: yes
  tasks:
  - name: Install NPM source
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: Install Nodejs
    ansible.builtin.yum:
      name: nodejs 
      state: installed

  - name: Checking whether roboshop user exists
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true

  - when: out.rc != 0
    name: add roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: checking the app directory
    ansible.builtin.stat: 
      path: /app
    register: directory

  - name: Printing the stat
    ansible.builtin.debug:
      msg: "Output is : {{directory}}"

  - when: directory.stat.exists == False
    name: Create app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Download the user artifact
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: Extracting the user artifact
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes


  - name: Installing dependencies
    ansible.builtin.command: npm install 
    args:
      chdir: /app

  - name: Copying user.service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: Daemon reload
    ansible.builtin.systemd:
      daemon_reload: true

  - name: Starting and enabling user
    ansible.builtin.service:
      name: user
      state: started
      enabled: true

  - name: Copying mongo repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installing mongo client
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: Loading mongo schema
    ansible.builtin.shell: mongo --host mongodb.sailasdevops.online </app/schema/user.js

  - name: Restart user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: true
